x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: airflow/Dockerfile
  image: apache/airflow:3.1.2
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"

    DB_HOST: host.docker.internal
    DB_PORT: "5432"
    DB_NAME: sales_dw
    DB_USER: postgres
    DB_PASSWORD: ${DB_PASSWORD}
    DBT_DB_HOST: host.docker.internal
    DBT_DB_PORT: "5432"
    DBT_DB_PASSWORD: ${DB_PASSWORD}

    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./airflow/config:/opt/airflow/config
    - ./src:/opt/airflow/src
    - ./data:/opt/airflow/data
    - ./dbt_project:/opt/airflow/dbt_project
  depends_on:
    - postgres

services:

  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres-airflow-data:/var/lib/postgresql

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate
    restart: "no"

  airflow:
    <<: *airflow-common
    command: standalone
    ports:
      - "8080:8080"

volumes:
  postgres-airflow-data: