dbt_project:
  target: dev

  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_DB_HOST') }}"
      port: "{{ env_var('DBT_DB_PORT') | int }}"
      user: postgres
      password: "{{ env_var('DBT_DB_PASSWORD') }}"
      dbname: sales_dw
      schema: warehouse
      threads: 4